permalink: /:categories/:year/:month/:title
highlighter: rouge
gems:
  - jekyll-redirect-from
navigation:
  - title: 홈
    url: /
  - title: Download
    url: "https://julialang.org/downloads/"
  - title: 문서
    url: "/ko/latest/"
    class: docs
  - title: Blog
    url: "https://julialang.org/blog/"
  - title: Community
    url: "https://julialang.org/community/"
  - title: Learn
    url: "https://julialang.org/learning/"
  - title: Research
    url: "https://julialang.org/research/"
  - title: JSoC
    url: "https://julialang.org/jsoc/"
collections:
  publications:
    permalink: /publications/:path
